#!/bin/bash -x
source sources.list 2>/dev/null

#Sudo?
set -e

echo "Checking nginx"

#Check nginx and install
nginx -v 2>/dev/null
if [[ ! $? = 0 ]] ;  
then apt-get update -y 

	sleep 10
apt-get install -y nginx 

sleep 10
fi
NGINX_STATUS=$(systemctl show nginx.service --property=ActiveState | sed s/ActiveState=//)
if [[  $NGINX_STATUS = "active"  ]];
then    echo "Nginx is active"
else
echo "Please start or activate Nginx"
fi

echo "nginx status is $NGINX_STATUS "
echo "NGINX Configuration starts"
#Configure nginx
echo '
server {
        listen 80;
        listen [::]:80;

        root /var/www/bootcamp_aca;
        
        index index.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }
} ' > /etc/nginx/sites-available/bootcamp_aca.conf && rm -rf /etc/nginx/sites-enabled/default && ln -s /etc/nginx/sites-available/bootcamp_aca.conf /etc/nginx/sites-enabled/bootcamp_aca.conf

echo "Nginx configured"


#Creating root folder
if [ ! -d /var/www/bootcamp_aca/ ] 
then 
	mkdir -p /var/www/bootcamp_aca/
fi
if [ -f /var/www/bootcamp_aca/index.html ]
then
	rm -f /var/www/bootcamp_aca/index.html
fi
echo "Root folder created"

#Downloading index.html from s3
sudo wget -O /var/www/bootcamp_aca/index.html --no-check-certificate --no-proxy https://aca-bootcamp-narek.s3.amazonaws.com/index.html
echo 'index.html downloaded'
echo done
